sudo: required
dist: trusty

language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
install: npm ci
jobs:
  include:
    - stage: build
      script:
        - npm run build
    - stage: test
      script:
        - npm run test
    - stage: release
      if: branch = master
      script:
        - npx semantic-release
          