dist: trusty
git:
  depth: false
language: node_js
env:
  global:
    - COMMITCOUNT="$(git log $(git describe --tags --abbrev=0)..HEAD --oneline | grep -iv "revert" |grep -e "fix(" -e "feat(" | wc -l | awk '{print $1}')"
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
before_install:
  - git log $(git describe --tags --abbrev=0)..HEAD --oneline
  - echo $COMMITCOUNT
install: 
  - npm config set package-lock false
  - make install

jobs:
  include:
    - script:
        - npm run build
      before_script: cd packages/server
      name: build-server
    - script:
        - npm run build
        - bin/run --version
      before_script: cd packages/cli
      name: build-cli
    - script:
        - npm run test
        - npx snyk test
      before_script: cd packages/server
      name: test-server
    - stage: release
      if: (type = push AND branch = master AND env(COMMITCOUNT) != 0)
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git fetch pub master
        - git checkout master
      script:
        - make fake-credentials
        - make publish