sudo: required
dist: trusty

language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
install: npm install
jobs:
  include:
    - stage: build
      script:
        - npm run build
    - stage: test
      script:
        - npm run test
      