# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-json-server

package:
  individually: false
  excludeDevDependencies: true
  include:
    - dist/**
    - node_modules/**
  exclude: 
    - src/**

custom: 
  s3bucket: ${self:service}-${self:provider.stage}-bucket
  s3jsonfile: ${self:service}-${self:provider.stage}-file.json

# The `provider` block defines where your service will be deployed
provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  runtime: nodejs8.10
  region: "eu-central-1"
  environment:
    S3BUCKET: ${self:custom.s3bucket}
    S3FILE: ${self:custom.s3jsonfile}
    READONLY: false

  apiKeys:
    - ${self:service}.${self:provider.stage}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: ServerlessDeploymentBucket
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
         - "s3:GetObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: ServerlessDeploymentBucket
             - "/*"
# The `functions` block defines what code to deploy
functions:
  app:
    handler: /dist/server.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http: 
          path: /
          method: ANY
          cors: true
          private: true
      - http: 
          path: "{proxy+}"
          method: ANY
          cors: true
          private: true
resources:
  Resources:
    ServerlessDeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3bucket}
